export enum MainRoutes {
  SPLASH_SCREEN = 'SPLASH_SCREEN',
  TAB_NAVIGATOR = 'TAB_NAVIGATOR'
}

export enum TabRoutes {
  HOME_STACK = 'HOME_STACK',
  SEARCH_SCREEN = 'SEARCH_SCREEN',
}

export enum HomeStackRoutes {
  SHOWS_LIST = 'SHOWS_LIST',
  SHOW_DETAIL_SCREEN = 'SHOW_DETAIL_SCREEN',
  EPISODE_DETAILS_SCREEN = 'EPISODE_DETAILS_SCREEN'
}